### ISSUE TITLE
Correction to website

### ISSUE THREAD

**Issue by mikemerryguy** [djGrrr/8311-was-110-firmware-builder#1]
The sites lists NGW320-500 and BGW300-505

the difference listed is a HUMAX amd NOKIA 

However that is wrong
Those are manufacturers 
The bgw320-500 is GPON frequency and the BGW320-505 is XGSPON frequency

Also the SFP module for XGS PON is RED nor orange and the GPIN Sfp is green.

**Comment by tkirkland** [comment]
Just verifying:
https://www.reddit.com/r/ATTFiber/comments/13c9jwk/difference_between_bgw320505_and_bgw320500/
![image](https://github.com/djGrrr/8311-was-110-firmware-builder/assets/18052612/d534098e-110c-4738-8e14-9a4fd8f5257a)
Maybe double-check because what's listed in the thread is accurate here.
